### ISSUE TITLE
Digitalocean Api 2.0

### ISSUE THREAD

**Issue by ghost** [jacobtomlinson/codeigniter-digitalocean#1]
Hi
Thanks for this programe
Do you plan to write Digitalocean Api 2.0?

**Comment by jacobtomlinson** [comment]
This module is just a port of https://github.com/Kuruka/DigitalOcean-PHP-Class to fit into CodeIgniter.

I have considered writing a V2 API but it would mean writing the whole module rather than just modifying someone elses code.

I would like to do it but it's fairly low on my list of things to work on.

Sorry

**Comment by ghost** [comment]
Thanks
Good luck,
